/* =============================================================================
   GhostDesk — Strategy Generator
   Obsidian Intelligence: AI generates Soul Engineer strategy docs
   ============================================================================= */

import { useState } from "react";
import AppLayout from "@/components/AppLayout";
import { FileText, Zap, Copy, Download, ChevronDown } from "lucide-react";
import { toast } from "sonner";

const TEMPLATES = [
  { id: "full", label: "Full Strategy Doc", desc: "Vibe Check + Engineering Map + Legacy Play + Next Beat" },
  { id: "quick", label: "Quick Audit", desc: "Pain points + 3 AI solutions + immediate next step" },
  { id: "deck", label: "Slide Deck Shell", desc: "5-slide structure ready for your brand colors" },
  { id: "email", label: "Outreach Email", desc: "Personalized first-touch email in your voice" },
];

const INDUSTRIES = [
  "Creative Agency", "Tech Startup", "Solo Founder", "Real Estate", "Healthcare",
  "E-commerce", "Coaching / Consulting", "Media / Publishing", "Finance", "Other"
];

const SAMPLE_OUTPUT = `# Soul Engineer Strategy — TechFlow Solutions

**Prepared by:** Ghost Consultant  
**Framework:** Soul Engineer v2.0  
**Date:** March 19, 2026  
**Confidence Score:** 8.4/10

---

## 01 — The Vibe Check

Marcus Chen and TechFlow Solutions are at a critical inflection point. The business has strong product-market fit and a growing client base, but the internal structure is fracturing under growth pressure. Three separate lead management tools, inconsistent onboarding, and a brand voice that shifts depending on which team member is writing — these are not operational problems. They are **structural problems of purpose**.

The core tension: Marcus wants to scale, but the systems he's built are designed for a solo operator. The AI implementation he's seeking isn't just about efficiency — it's about rebuilding the internal architecture so the business can grow without Marcus being the single point of failure.

---

## 02 — The Engineering Map

**Tool 1: Unified Lead Intelligence Pipeline**  
Deploy a lead scoring and qualification system that automatically pulls from LinkedIn, email, and social mentions. Every lead gets a Soul Engineer audit score (1–10) before Marcus sees it. He only engages with leads scoring 7+. Estimated time savings: 4 hours/week.

**Tool 2: AI-Powered Onboarding Assistant**  
Build a RAG-based assistant trained on TechFlow's service documentation, past client deliverables, and Marcus's communication style. New clients get a personalized onboarding experience that feels like Marcus wrote it — because the AI learned from him.

**Tool 3: Content Repurposing Engine**  
One recorded client call or podcast appearance becomes: 3 LinkedIn posts, 2 email newsletters, 1 YouTube short, and a blog post. All in Marcus's voice. Estimated content output increase: 8x with no additional time investment.

---

## 03 — The Legacy Play

The real opportunity here isn't just operational efficiency — it's **category creation**. TechFlow has the chance to become the first AI-native consulting firm in the B2B SaaS implementation space. The play: build a public "AI Implementation Playbook" — a living document updated monthly with real case studies from TechFlow's client work.

This becomes a lead magnet, a thought leadership asset, and eventually a paid product. In 18 months, this playbook is what TechFlow is known for — not just the services they provide.

---

## 04 — The Next Beat

**Immediate action:** Schedule a 30-minute "AI Architecture Audit" call with Marcus. Come prepared with:
- His current tech stack mapped against the Soul Engineer framework
- 3 specific automation opportunities ranked by ROI
- A rough timeline for a 90-day implementation sprint

**Proposed offer:** AI Implementation Sprint — $12,000 for 90 days. Deliverables: unified lead pipeline, onboarding assistant, and content engine. Ongoing retainer: $2,500/month for maintenance and optimization.

---

*Generated by GhostDesk — Soul Engineer Framework*`;

export default function StrategyGen() {
  const [selectedTemplate, setSelectedTemplate] = useState("full");
  const [clientName, setClientName] = useState("");
  const [company, setCompany] = useState("");
  const [industry, setIndustry] = useState("");
  const [context, setContext] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [output, setOutput] = useState("");
  const [genStep, setGenStep] = useState(0);

  const GEN_STEPS = [
    "Loading Soul Engineer framework...",
    "Analyzing client context...",
    "Applying Internal Structure lens...",
    "Mapping Engineering solutions...",
    "Crafting Legacy Play...",
    "Finalizing strategy document...",
    "Document ready.",
  ];

  const handleGenerate = () => {
    if (!clientName.trim() || !company.trim()) {
      toast.error("Please enter at least a client name and company.");
      return;
    }
    setIsGenerating(true);
    setOutput("");
    setGenStep(0);
    let step = 0;
    const stepInterval = setInterval(() => {
      step++;
      setGenStep(step);
      if (step >= GEN_STEPS.length - 1) {
        clearInterval(stepInterval);
        // Simulate typewriter output
        let charIndex = 0;
        const typeInterval = setInterval(() => {
          charIndex += 8;
          setOutput(SAMPLE_OUTPUT.slice(0, charIndex));
          if (charIndex >= SAMPLE_OUTPUT.length) {
            clearInterval(typeInterval);
            setIsGenerating(false);
            toast.success("Strategy document generated!");
          }
        }, 20);
      }
    }, 500);
  };

  return (
    <AppLayout title="Strategy Generator" subtitle="Soul Engineer document engine">
      <div className="p-6">
        <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">

          {/* Left: Config Panel */}
          <div className="lg:col-span-2 space-y-4">

            {/* Template Selection */}
            <div style={{ background: 'var(--surface)', border: '1px solid var(--border-subtle)' }}>
              <div className="px-4 py-3" style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                <div style={{ fontFamily: 'Playfair Display, serif', fontSize: '15px', fontWeight: 600, color: 'var(--text-primary)' }}>
                  Output Type
                </div>
              </div>
              <div className="p-3 space-y-2">
                {TEMPLATES.map((t) => (
                  <button
                    key={t.id}
                    onClick={() => setSelectedTemplate(t.id)}
                    className="w-full text-left p-3 transition-all duration-150"
                    style={{
                      background: selectedTemplate === t.id ? 'var(--amber-glow)' : 'var(--surface-raised)',
                      border: `1px solid ${selectedTemplate === t.id ? 'var(--border-amber)' : 'var(--border-subtle)'}`,
                      borderLeft: `2px solid ${selectedTemplate === t.id ? 'var(--amber)' : 'transparent'}`,
                    }}
                  >
                    <div style={{ fontSize: '13px', fontWeight: 500, color: selectedTemplate === t.id ? 'var(--amber)' : 'var(--text-primary)' }}>
                      {t.label}
                    </div>
                    <div className="data-label mt-0.5">{t.desc}</div>
                  </button>
                ))}
              </div>
            </div>

            {/* Client Details */}
            <div style={{ background: 'var(--surface)', border: '1px solid var(--border-subtle)' }}>
              <div className="px-4 py-3" style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                <div style={{ fontFamily: 'Playfair Display, serif', fontSize: '15px', fontWeight: 600, color: 'var(--text-primary)' }}>
                  Client Details
                </div>
              </div>
              <div className="p-4 space-y-3">
                <div>
                  <label className="data-label block mb-1.5">Client Name</label>
                  <input
                    type="text"
                    value={clientName}
                    onChange={(e) => setClientName(e.target.value)}
                    placeholder="Marcus Chen"
                    className="ghost-input w-full px-3 py-2.5 text-sm"
                    style={{ borderRadius: '2px' }}
                  />
                </div>
                <div>
                  <label className="data-label block mb-1.5">Company</label>
                  <input
                    type="text"
                    value={company}
                    onChange={(e) => setCompany(e.target.value)}
                    placeholder="TechFlow Solutions"
                    className="ghost-input w-full px-3 py-2.5 text-sm"
                    style={{ borderRadius: '2px' }}
                  />
                </div>
                <div>
                  <label className="data-label block mb-1.5">Industry</label>
                  <div className="relative">
                    <select
                      value={industry}
                      onChange={(e) => setIndustry(e.target.value)}
                      className="ghost-input w-full px-3 py-2.5 text-sm appearance-none"
                      style={{ borderRadius: '2px' }}
                    >
                      <option value="">Select industry...</option>
                      {INDUSTRIES.map((ind) => (
                        <option key={ind} value={ind}>{ind}</option>
                      ))}
                    </select>
                    <ChevronDown
                      size={14}
                      className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none"
                      style={{ color: 'var(--text-muted)' }}
                    />
                  </div>
                </div>
                <div>
                  <label className="data-label block mb-1.5">Context / Notes</label>
                  <textarea
                    value={context}
                    onChange={(e) => setContext(e.target.value)}
                    placeholder="Paste their LinkedIn bio, email, pain points, or any relevant context..."
                    rows={5}
                    className="ghost-input w-full px-3 py-2.5 text-sm resize-none"
                    style={{ borderRadius: '2px' }}
                  />
                </div>

                <button
                  onClick={handleGenerate}
                  disabled={isGenerating}
                  className="w-full flex items-center justify-center gap-2 py-3 transition-all duration-150"
                  style={{
                    background: isGenerating ? 'var(--amber-dim)' : 'var(--amber)',
                    color: 'var(--obsidian)',
                    fontWeight: 600,
                    fontSize: '14px',
                    fontFamily: 'DM Sans, sans-serif',
                    opacity: isGenerating ? 0.7 : 1,
                  }}
                >
                  {isGenerating ? (
                    <>
                      <span className="status-dot processing" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Zap size={15} />
                      Generate Strategy
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>

          {/* Right: Output Panel */}
          <div className="lg:col-span-3">
            <div
              style={{
                background: 'var(--surface)',
                border: '1px solid var(--border-subtle)',
                minHeight: '600px',
                display: 'flex',
                flexDirection: 'column',
              }}
            >
              <div
                className="flex items-center justify-between px-5 py-3.5"
                style={{ borderBottom: '1px solid var(--border-subtle)' }}
              >
                <div className="flex items-center gap-3">
                  <FileText size={15} style={{ color: 'var(--amber)' }} />
                  <span style={{ fontFamily: 'Playfair Display, serif', fontSize: '15px', fontWeight: 600, color: 'var(--text-primary)' }}>
                    Strategy Output
                  </span>
                  {isGenerating && <span className="status-dot processing" />}
                  {output && !isGenerating && <span className="ghost-badge">Ready</span>}
                </div>
                {output && (
                  <div className="flex gap-2">
                    <button
                      onClick={() => { navigator.clipboard.writeText(output); toast.success("Copied to clipboard"); }}
                      className="flex items-center gap-1.5 px-3 py-1.5 text-xs transition-all duration-150"
                      style={{ border: '1px solid var(--border-subtle)', color: 'var(--text-secondary)', fontFamily: 'DM Sans, sans-serif' }}
                    >
                      <Copy size={11} /> Copy
                    </button>
                    <button
                      onClick={() => toast.info("Export coming soon")}
                      className="flex items-center gap-1.5 px-3 py-1.5 text-xs transition-all duration-150"
                      style={{ border: '1px solid var(--border-subtle)', color: 'var(--text-secondary)', fontFamily: 'DM Sans, sans-serif' }}
                    >
                      <Download size={11} /> Export
                    </button>
                  </div>
                )}
              </div>

              <div className="flex-1 p-5 overflow-y-auto">
                {/* Generation Progress */}
                {isGenerating && genStep < GEN_STEPS.length - 1 && (
                  <div className="mb-4 p-4 fade-in-up" style={{ background: 'var(--amber-glow)', border: '1px solid var(--border-amber)' }}>
                    <div className="space-y-1.5">
                      {GEN_STEPS.map((step, i) => (
                        <div
                          key={i}
                          className="flex items-center gap-2"
                          style={{ opacity: i <= genStep ? 1 : 0.2, transition: 'opacity 300ms ease' }}
                        >
                          <div
                            style={{
                              width: '5px', height: '5px', borderRadius: '50%', flexShrink: 0,
                              background: i < genStep ? '#4ADE80' : i === genStep ? 'var(--amber)' : 'var(--text-muted)',
                            }}
                          />
                          <span style={{ fontFamily: 'Fira Code, monospace', fontSize: '11px', color: i === genStep ? 'var(--amber)' : i < genStep ? '#4ADE80' : 'var(--text-muted)' }}>
                            {step}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Output */}
                {output ? (
                  <div
                    style={{
                      fontFamily: 'DM Sans, sans-serif',
                      fontSize: '13px',
                      color: 'var(--text-secondary)',
                      lineHeight: 1.8,
                      whiteSpace: 'pre-wrap',
                    }}
                  >
                    {output.split('\n').map((line, i) => {
                      if (line.startsWith('# ')) return (
                        <h1 key={i} style={{ fontFamily: 'Playfair Display, serif', fontSize: '20px', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '8px', marginTop: '16px' }}>
                          {line.replace('# ', '')}
                        </h1>
                      );
                      if (line.startsWith('## ')) return (
                        <h2 key={i} style={{ fontFamily: 'Playfair Display, serif', fontSize: '15px', fontWeight: 600, color: 'var(--amber)', marginBottom: '6px', marginTop: '20px' }}>
                          {line.replace('## ', '')}
                        </h2>
                      );
                      if (line.startsWith('**') && line.endsWith('**')) return (
                        <div key={i} style={{ fontWeight: 600, color: 'var(--text-primary)', marginBottom: '4px' }}>
                          {line.replace(/\*\*/g, '')}
                        </div>
                      );
                      if (line === '---') return <div key={i} className="amber-rule my-4" />;
                      return <div key={i}>{line || <br />}</div>;
                    })}
                  </div>
                ) : !isGenerating ? (
                  <div className="flex flex-col items-center justify-center h-full text-center" style={{ minHeight: '400px' }}>
                    <div
                      style={{
                        width: '60px',
                        height: '60px',
                        background: 'var(--amber-glow)',
                        border: '1px solid var(--border-amber)',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        marginBottom: '16px',
                      }}
                    >
                      <FileText size={24} style={{ color: 'var(--amber)', opacity: 0.6 }} />
                    </div>
                    <div style={{ fontFamily: 'Playfair Display, serif', fontSize: '16px', color: 'var(--text-secondary)' }}>
                      Strategy awaiting generation
                    </div>
                    <div className="data-label mt-2">Fill in client details and click Generate Strategy</div>
                  </div>
                ) : null}
              </div>
            </div>
          </div>

        </div>
      </div>
    </AppLayout>
  );
}
