import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";

const EFFECTIVE_DATE = "April 10, 2026";
const CONTACT_EMAIL = "legal@operatorhousehq.com";

export default function Terms() {
  return (
    <div className="min-h-screen" style={{ background: "var(--obsidian)", color: "var(--text-primary)" }}>
      {/* Nav */}
      <div className="sticky top-0 z-10 flex items-center gap-3 px-6 py-4" style={{ background: "var(--obsidian)", borderBottom: "1px solid var(--border-subtle)" }}>
        <Link href="/" className="flex items-center gap-2 text-sm" style={{ color: "var(--text-muted)", textDecoration: "none" }}>
          <ArrowLeft size={14} />
          Back
        </Link>
        <span style={{ color: "var(--border-subtle)" }}>|</span>
        <span style={{ fontSize: "13px", fontFamily: "Fira Code, monospace", color: "var(--amber)" }}>Terms of Service</span>
      </div>

      {/* Content */}
      <div className="max-w-2xl mx-auto px-6 py-12 space-y-8">
        <div>
          <h1 style={{ fontFamily: "Playfair Display, serif", fontSize: "32px", fontWeight: 700, color: "var(--ivory)" }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: "13px", color: "var(--text-muted)", marginTop: "8px", fontFamily: "DM Sans, sans-serif" }}>
            Effective date: {EFFECTIVE_DATE}
          </p>
        </div>

        {[
          {
            title: "1. Acceptance of Terms",
            body: "By accessing or using Operator House, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the service. These terms apply to all users of the application.",
          },
          {
            title: "2. Description of Service",
            body: "Operator House is an AI-powered consulting command center that provides lead intelligence, pipeline management, strategy generation, knowledge vault storage, analytics, and an AI assistant. The service is provided on an \"as is\" and \"as available\" basis.",
          },
          {
            title: "3. Eligibility",
            body: "You must be at least 18 years old and capable of forming a binding contract to use this service. By using Operator House, you represent that you meet these requirements.",
          },
          {
            title: "4. User Accounts",
            body: "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to terminate accounts that violate these terms.",
          },
          {
            title: "5. Acceptable Use",
            body: "You agree not to use Operator House to: (a) violate any applicable law or regulation; (b) transmit any content that is unlawful, harmful, or fraudulent; (c) attempt to gain unauthorized access to any part of the service; (d) use automated tools to scrape or abuse the AI endpoints beyond normal use; or (e) resell or sublicense access to the service without written permission.",
          },
          {
            title: "6. Content Ownership",
            body: "You retain full ownership of all content you create or upload to Operator House, including leads, vault items, strategies, and pipeline data. By using the service, you grant us a limited license to process and store your content solely for the purpose of providing the service to you. We do not claim ownership of your content.",
          },
          {
            title: "7. AI-Generated Content",
            body: "Content generated by the AI features of Operator House (lead audits, strategies, briefings, chat responses) is provided for informational and productivity purposes only. It does not constitute legal, financial, or professional advice. You are solely responsible for how you use AI-generated content in your business.",
          },
          {
            title: "8. Service Availability",
            body: "We do not guarantee uninterrupted or error-free access to the service. We may suspend or discontinue the service at any time with reasonable notice. We are not liable for any losses resulting from service interruptions.",
          },
          {
            title: "9. Limitation of Liability",
            body: "To the maximum extent permitted by law, Operator House and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service, including loss of data, loss of revenue, or loss of business opportunities.",
          },
          {
            title: "10. Indemnification",
            body: "You agree to indemnify and hold harmless Operator House and its operators from any claims, damages, or expenses (including reasonable legal fees) arising from your use of the service, your violation of these terms, or your violation of any third-party rights.",
          },
          {
            title: "11. Termination",
            body: "You may terminate your account at any time by using the Delete Account feature in Settings. We may terminate or suspend your account for violations of these terms. Upon termination, your right to use the service ceases immediately and your data will be deleted in accordance with our Privacy Policy.",
          },
          {
            title: "12. Changes to Terms",
            body: "We may update these Terms of Service as the service evolves. We will notify you of material changes by updating the effective date at the top of this page. Continued use of the service after changes constitutes acceptance of the updated terms.",
          },
          {
            title: "13. Governing Law",
            body: "These terms are governed by the laws of the United States. Any disputes arising from these terms or your use of the service shall be resolved through binding arbitration in accordance with the American Arbitration Association rules.",
          },
          {
            title: "14. Contact",
            body: `For questions about these Terms of Service, contact us at ${CONTACT_EMAIL}.`,
          },
        ].map(({ title, body }) => (
          <div key={title}>
            <h2 style={{ fontFamily: "DM Sans, sans-serif", fontSize: "15px", fontWeight: 700, color: "var(--ivory)", marginBottom: "8px" }}>
              {title}
            </h2>
            <p style={{ fontFamily: "DM Sans, sans-serif", fontSize: "14px", color: "var(--text-secondary)", lineHeight: 1.7 }}>
              {body}
            </p>
          </div>
        ))}

        <div style={{ borderTop: "1px solid var(--border-subtle)", paddingTop: "24px" }}>
          <Link href="/privacy" style={{ fontSize: "13px", color: "var(--amber)", textDecoration: "none", fontFamily: "DM Sans, sans-serif" }}>
            View Privacy Policy →
          </Link>
        </div>
      </div>
    </div>
  );
}
